name: Generate Podcast Feed

on:
  push:
    paths:
      - feed.yaml
      - .github/workflows/**

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Podcast Generator Action
        uses: cemakcck/podcast-generator@main
